// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7BfZGTZOSY4XgyiHmXMBqlaJ7LoYs8w',
    appId: '1:360712574434:web:5b5f82fc446a54020b15bb',
    messagingSenderId: '360712574434',
    projectId: 'authenticationtest-d4ad2',
    authDomain: 'authenticationtest-d4ad2.firebaseapp.com',
    storageBucket: 'authenticationtest-d4ad2.firebasestorage.app',
    measurementId: 'G-G3BH2ZXWJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAW8l29UwrzpkZyxBpOwjhOuvtuyAkz2I',
    appId: '1:360712574434:android:1eb80b14f6e8284c0b15bb',
    messagingSenderId: '360712574434',
    projectId: 'authenticationtest-d4ad2',
    storageBucket: 'authenticationtest-d4ad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYFTJxOHTKJY8VM7ZKq0T8U6FAqwT4Z1E',
    appId: '1:360712574434:ios:24abb183cc40f4fc0b15bb',
    messagingSenderId: '360712574434',
    projectId: 'authenticationtest-d4ad2',
    storageBucket: 'authenticationtest-d4ad2.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYFTJxOHTKJY8VM7ZKq0T8U6FAqwT4Z1E',
    appId: '1:360712574434:ios:24abb183cc40f4fc0b15bb',
    messagingSenderId: '360712574434',
    projectId: 'authenticationtest-d4ad2',
    storageBucket: 'authenticationtest-d4ad2.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG7BfZGTZOSY4XgyiHmXMBqlaJ7LoYs8w',
    appId: '1:360712574434:web:b5aa602ca2d5c6ff0b15bb',
    messagingSenderId: '360712574434',
    projectId: 'authenticationtest-d4ad2',
    authDomain: 'authenticationtest-d4ad2.firebaseapp.com',
    storageBucket: 'authenticationtest-d4ad2.firebasestorage.app',
    measurementId: 'G-C5TGS4123C',
  );
}
